name: Runner test

on:
  workflow_dispatch:
  push:
    branches: [mini-project-2]

jobs:
  check:
    runs-on: [self-hosted, mlflow-local]
    steps:
      - uses: actions/checkout@v4
      - run: whoami && pwd
      - run: curl -sf http://localhost:5000/health && echo "MLflow reachable"
      - run: curl -sf http://localhost:9000/minio/health/live && echo "MinIO reachable"